org: hhassan
app: orbital-serverless
service: reporting-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    MONGODB_URI: "mongodb+srv://root:orbital-password@orbital-test-0.5brqv.mongodb.net/?retryWrites=true&w=majority&appName=orbital-test-0"
    # MONGODB_URI: ${ssm:/accounts-service/MONGODB_URI}
    # EVENT_BUS_NAME: ${ssm:/my-service/EVENT_BUS_NAME~true}
  
  
functions:
  transactionEventListener:
    handler: src/handlers/transactionEventListener.handler
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - 'accounts-service'
            detail-type:
              - 'TransactionCreated'
              - 'AccountCreated'
              - 'AccountUpdated'
  
  getMonthlyStatements:
    handler: src/handlers/getMonthlyStatements.handler
    events:
      - http:
          path: statements/{accountId}/{year}/{month}
          method: get
  
resources:
  Resources:
    TransactionEventListenerLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::GetAtt:
            - TransactionEventListenerLambdaFunction
            - Arn
        Principal: events.amazonaws.com
        SourceArn:
          Fn::GetAtt:
            - TransactionEventListenerEventRule
            - Arn

    TransactionEventListenerEventRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: default
        EventPattern:
          source:
            - 'accounts-service'
          detail-type:
              - 'TransactionCreated'
              - 'AccountCreated'
              - 'AccountUpdated'
        Targets:
          - Arn:
              Fn::GetAtt:
                - TransactionEventListenerLambdaFunction
                - Arn
            Id: "TransactionEventListenerTarget"

package:
  individually: true
  exclude:
    - coverage/**
    - tests/**
    - jest.config.js
    - README.md
    - .prettierrc
    - .gitignore
    - .git/**
    - .github/**

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: "node20"
    platform: "node"
    exclude: 
      - "jest"
      - "mongodb-memory-server"
      - "prettier"