org: hhassan
app: orbital-serverless
service: reporting-service  

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    MONGODB_URI: ${param:MONGODB_URI}
    EVENT_BUS_NAME: ${param:EVENT_BUS_NAME}
    AWS_REGION: ${param:AWS_REGION}
  
functions:
  transactionEventListener:
    handler: src/handlers/transactionEventListener.handler
    events:
      - eventBridge:
          eventBus: ${param:EVENT_BUS_NAME}
          pattern:
            source:
              - ${param:EVENT_SOURCE}
            detail-type:
              - ${param:EVENT_DETAIL_TYPE}
  
  getMonthlyStatements:
    handler: dist/src/handlers/getMonthlyStatements.handler
    events:
      - http:
          path: statements/{accountId}/{year}/{month}
          method: get
  
resources:
  Resources:
    TransactionEventListenerLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::GetAtt:
            - TransactionEventListenerLambdaFunction
            - Arn
        Principal: events.amazonaws.com
        SourceArn:
          Fn::GetAtt:
            - TransactionEventListenerEventRule
            - Arn

    TransactionEventListenerEventRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: ${param:EVENT_BUS_NAME}
        EventPattern:
          source:
            - ${param:EVENT_SOURCE}
          detail-type:
              - ${param:EVENT_DETAIL_TYPE}
        Targets:
          - Arn:
              Fn::GetAtt:
                - TransactionEventListenerLambdaFunction
                - Arn
            Id: "TransactionEventListenerTarget"

package:
  individually: true
  exclude:
    - coverage/**
    - tests/**
    - jest.config.js
    - README.md
    - .prettierrc
    - .gitignore
    - .git/**
    - .github/**

plugins:
  - serverless-offline

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: "node20"
    platform: "node"
    exclude: 
      - "jest"
      - "mongodb-memory-server"
      - "prettier"